[package]
name = "dupefindr"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
clap = { version = "4.5.27", features = ["derive"] }
glob = "0.3.2"
indicatif = "0.17.9"
md-5 = "0.10.6"
num_cpus = "1.16.0"
threadpool = "1.8.1"
